#!/bin/bash

echo "1. Addition"
echo "2. Subtraction"
echo "3. Multiplication"
echo "4. Divition"

read -p "Choose an Operation from 1 to 4: " input

if [ $input -eq 1 ]; then
        read -p "Enter the first number: " x
        read -p "Enter the second number: " y
        Add=$((x + y))
        echo "Result: $Add"

elif [ $input -eq 2 ]; then
        read -p "Enter the first number: " x
        read -p "Enter the second number: " y
        Sub=$((x - y))
        echo "Result: $Sub"

elif [ $input -eq 3 ]; then
        read -p "Enter the first number: " x
        read -p "Enter the second number: " y
        Mul=$((x * y))
        echo "Result: $Mul"

elif [ $input -eq 4 ]; then
        read -p "Enter the first number: " x
        read -p "Enter the second number: " y
        Divs=$((x / y))
        echo "Result: $Divs"
fi

